src/Pos.WebApplication/Models/ErrorViewModel.cs
using System;

namespace Pos.WebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/Pos.WebApplication/Models/MenuItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pos.WebApplication.Models
{
    public class MenuItem
    {
        public Guid Id { get; set; }
        public Guid? Parent { get; set; }
        public string Title { get; set; }
        public string Icon { get; set; }
        public string Url { get; set; }
        public int Position { get; set; }
        public bool OpenInNewWindow { get; set; }
    }
}

src/Pos.WebApplication/Areas/Master/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pos.WebApplication.Areas.Masters.Controllers
{
    [Area("Master")]
    public class CustomerController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Pos.WebApplication/Areas/Master/Controllers/ProductCategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pos.WebApplication.Areas.Masters.Controllers
{
    [Area("Master")]
    public class ProductCategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Pos.WebApplication/Areas/Master/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pos.WebApplication.Areas.Masters.Controllers
{
    [Area("Master")]
    public class ProductController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Pos.WebApplication/Areas/Order/Controllers/ItemController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pos.WebApplication.Areas.Masters.Controllers
{
    [Area("Order")]
    public class ItemController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Pos.WebApplication/Areas/Reports/Controllers/TransactionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Pos.WebApplication.Areas.Masters.Controllers
{
    [Area("Reports")]
    public class TransactionController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/Pos.WebApplication/Controllers/AuthController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pos.WebApplication.Models;

namespace Pos.WebApplication.Controllers
{
    public class AuthController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Pos.WebApplication/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Pos.WebApplication.Models;

namespace Pos.WebApplication.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/Pos.WebApplication/ViewComponents/FooterViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pos.WebApplication.ViewComponents
{
    public class FooterViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Pos.WebApplication/ViewComponents/HeaderViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pos.WebApplication.ViewComponents
{
    public class HeaderViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Pos.WebApplication/ViewComponents/MenuViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Pos.WebApplication.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pos.WebApplication.ViewComponents
{
    public class MenuViewComponent : ViewComponent
    {
        private readonly List<MenuItem> _menus;

        public MenuViewComponent()
        {

            _menus = new List<MenuItem>
            {
                new MenuItem { Id = Guid.NewGuid(), Position = 1, Title = "Dashboard", Url = "/Home", Icon = "md md-dashboard" },
                new MenuItem { Id = Guid.NewGuid(), Position = 2, Title = "Master", Url = "/Master", Icon = "md md-group" },
                new MenuItem { Id = Guid.NewGuid(), Position = 3, Title = "Order", Url = "/Order/Item", Icon = "md md-shopping-cart" },
                new MenuItem { Id = Guid.NewGuid(), Position = 4, Title = "Report", Url = "/Reports/Transaction", Icon = "md md-today" },                
            };

            _menus.Add(new MenuItem { Id = Guid.NewGuid(), Position = 1, Title = "Product", Url = "/Master/Product", Icon = "md md-account-child", Parent = _menus.Where(x => x.Title.Contains("Master")).SingleOrDefault().Id });
            _menus.Add(new MenuItem { Id = Guid.NewGuid(), Position = 2, Title = "Product Category", Url = "/Master/ProductCategory", Icon = "md md-account-child", Parent = _menus.Where(x => x.Title.Contains("Master")).SingleOrDefault().Id });
            _menus.Add(new MenuItem { Id = Guid.NewGuid(), Position = 3, Title = "Customer", Url = "/Master/Customer", Icon = "md md-account-child", Parent = _menus.Where(x => x.Title.Contains("Master")).SingleOrDefault().Id });




        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default", _menus));
        }
    }
}

src/Pos.WebApplication/ViewComponents/RightSidebarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pos.WebApplication.ViewComponents
{
    public class RightSidebarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Pos.WebApplication/ViewComponents/ThemeScriptsViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pos.WebApplication.ViewComponents
{
    public class ThemeScriptsViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Pos.WebApplication/ViewComponents/TopBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pos.WebApplication.ViewComponents
{
    public class TopBarViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync()
        {
            return await Task.FromResult((IViewComponentResult)View("Default"));
        }
    }
}

src/Pos.WebApplication/Areas/Master/Views/Product/Index.cshtml
@{
    ViewData["Title"] = "Product";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{        
    <link href="~/theme2-assets/plugins/bootstrap-table/css/bootstrap-table.min.css" rel="stylesheet" type="text/css" />
}


<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-header-box">
            <ol class="breadcrumb pull-right mb-0">
                <li class="breadcrumb-item"><a href="#">Pos</a></li>
                <li class="breadcrumb-item"><a href="#">Master</a></li>
                <li class="breadcrumb-item active">Product</li>
            </ol>
            <h4 class="page-title">Product</h4>
            <div class="clearfix"></div>
        </div>

    </div>
</div>


<!--Basic Toolbar-->
<!--===================================================-->
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <button class="btn btn-warning waves-effect waves-light"> <i class="fa fa-plus-circle"></i> <span>Insert</span> </button>
            <div class="fileupload btn btn-purple waves-effect waves-light">
                <span><i class="ion-upload m-r-5"></i>Import</span>
                <input type="file" class="upload">
            </div>
            <button class="btn btn-dark waves-effect waves-light"> <i class="fa fa-file-o"></i> <span>Export</span> </button>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Basic Toolbar</b></h4>
            <p class="text-muted font-13">
                Example of Basic Toolbar (Your text goes here).
            </p>

            <table data-toggle="table"
                   data-search="true"
                   data-show-refresh="true"
                   data-show-toggle="true"
                   data-show-columns="true"
                   data-sort-name="id"
                   data-page-list="[5, 10, 20]"
                   data-page-size="5"
                   data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">
                <thead>
                    <tr>
                        <th data-field="id" data-sortable="true" data-formatter="invoiceFormatter">Order ID</th>
                        <th data-field="name" data-sortable="true">Name</th>
                        <th data-field="date" data-sortable="true" data-formatter="dateFormatter">Order Date</th>
                        <th data-field="amount" data-align="center" data-sortable="true" data-sorter="priceSorter">Price</th>
                        <th data-field="status" data-align="center" data-sortable="true" data-formatter="statusFormatter">Status</th>

                    </tr>
                </thead>


                <tbody>
                    <tr>
                        <td>UB-1609</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1610</td>
                        <td>Woldt</td>
                        <td>24 Jun 2015</td>
                        <td>$ 15.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1611</td>
                        <td>Leonardo</td>
                        <td>25 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1612</td>
                        <td>Halladay</td>
                        <td>27 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>

                    <tr>
                        <td>UB-1613</td>
                        <td>Badgett</td>
                        <td>28 Jun 2015</td>
                        <td>$ 95.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1614</td>
                        <td>Boudreaux</td>
                        <td>29 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1615</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1616</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>

                    <tr>
                        <td>UB-1617</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1618</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1619</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1620</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>

                    <tr>
                        <td>UB-1621</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1622</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1623</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1624</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts{
    <!-- Bootsrap table js -->
    <script src="~/theme2-assets/plugins/bootstrap-table/js/bootstrap-table.js"></script>
    <script src="~/theme2-assets/pages/jquery.bs-table.js"></script>
}

src/Pos.WebApplication/Areas/Master/Views/ProductCategory/Index.cshtml
@{
    ViewData["Title"] = "Customer";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Styles{
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="~/theme2-assets/plugins/morris/morris.css">
    <link href="~/theme2-assets/plugins/bootstrap-table/css/bootstrap-table.min.css" rel="stylesheet" type="text/css" />
}


<!-- Page-Title -->
<div class="row">
    <div class="col-sm-12">
        <div class="page-header-box">
            <ol class="breadcrumb pull-right mb-0">
                <li class="breadcrumb-item"><a href="#">Pos</a></li>
                <li class="breadcrumb-item"><a href="#">Master</a></li>
                <li class="breadcrumb-item active">Product Category</li>
            </ol>
            <h4 class="page-title">Product Category</h4>
            <div class="clearfix"></div>
        </div>

    </div>
</div>


<!--Basic Toolbar-->
<!--===================================================-->
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <button class="btn btn-warning waves-effect waves-light"> <i class="fa fa-plus-circle"></i> <span>Insert</span> </button>
            <div class="fileupload btn btn-purple waves-effect waves-light">
                <span><i class="ion-upload m-r-5"></i>Import</span>
                <input type="file" class="upload">
            </div>
            <button class="btn btn-dark waves-effect waves-light"> <i class="fa fa-file-o"></i> <span>Export</span> </button>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <div class="card-box">
            <h4 class="m-t-0 header-title"><b>Basic Toolbar</b></h4>
            <p class="text-muted font-13">
                Example of Basic Toolbar (Your text goes here).
            </p>

            <table data-toggle="table"
                   data-search="true"
                   data-show-refresh="true"
                   data-show-toggle="true"
                   data-show-columns="true"
                   data-sort-name="id"
                   data-page-list="[5, 10, 20]"
                   data-page-size="5"
                   data-pagination="true" data-show-pagination-switch="true" class="table-bordered ">
                <thead>
                    <tr>
                        <th data-field="id" data-sortable="true" data-formatter="invoiceFormatter">Order ID</th>
                        <th data-field="name" data-sortable="true">Name</th>
                        <th data-field="date" data-sortable="true" data-formatter="dateFormatter">Order Date</th>
                        <th data-field="amount" data-align="center" data-sortable="true" data-sorter="priceSorter">Price</th>
                        <th data-field="status" data-align="center" data-sortable="true" data-formatter="statusFormatter">Status</th>

                    </tr>
                </thead>


                <tbody>
                    <tr>
                        <td>UB-1609</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1610</td>
                        <td>Woldt</td>
                        <td>24 Jun 2015</td>
                        <td>$ 15.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1611</td>
                        <td>Leonardo</td>
                        <td>25 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1612</td>
                        <td>Halladay</td>
                        <td>27 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>

                    <tr>
                        <td>UB-1613</td>
                        <td>Badgett</td>
                        <td>28 Jun 2015</td>
                        <td>$ 95.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1614</td>
                        <td>Boudreaux</td>
                        <td>29 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1615</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1616</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>

                    <tr>
                        <td>UB-1617</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1618</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1619</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1620</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>

                    <tr>
                        <td>UB-1621</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Unpaid</td>
                    </tr>
                    <tr>
                        <td>UB-1622</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Paid</td>
                    </tr>

                    <tr>
                        <td>UB-1623</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Shipped</td>
                    </tr>

                    <tr>
                        <td>UB-1624</td>
                        <td>Boudreaux</td>
                        <td>22 Jun 2015</td>
                        <td>$ 35.00</td>
                        <td>Refunded</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts{
    <!-- Bootsrap table js -->
    <script src="~/theme2-assets/plugins/bootstrap-table/js/bootstrap-table.js"></script>
    <script src="~/theme2-assets/pages/jquery.bs-table.js"></script>
}

src/Pos.WebApplication/Views/Shared/Components/Footer/Default.cshtml
<footer class="footer text-right">
    &copy; 2019. All rights reserved.
</footer>

src/Pos.WebApplication/Views/Shared/Components/Header/Default.cshtml
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="description" content="A fully featured admin theme which can be used to build CRM, CMS, etc.">
<meta name="author" content="Coderthemes">

<link rel="shortcut icon" href="~/theme2-assets/images/favicon.ico">

<title>POS</title>

<link rel="stylesheet" href="~/theme2-assets/plugins/morris/morris.css">
<link href="~/theme2-assets/plugins/bootstrap-sweetalert/sweet-alert.css" rel="stylesheet" type="text/css">


<link href="~/theme2-assets/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
<link href="~/theme2-assets/css/icons.css" rel="stylesheet" type="text/css" />
<link href="~/theme2-assets/css/style.css" rel="stylesheet" type="text/css" />

<script src="~/theme2-assets/js/modernizr.min.js"></script>   

src/Pos.WebApplication/Views/Shared/Components/RightSidebar/Default.cshtml
<div class="side-bar right-bar nicescroll">
    <h4 class="text-center">Chat</h4>
    <div class="contact-list nicescroll">
        <ul class="list-group contacts-list">
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-1.jpg" alt="">
                    </div>
                    <span class="name">Chadengle</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-2.jpg" alt="">
                    </div>
                    <span class="name">Tomaslau</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-3.jpg" alt="">
                    </div>
                    <span class="name">Stillnotdavid</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-4.jpg" alt="">
                    </div>
                    <span class="name">Kurafire</span>
                    <i class="fa fa-circle online"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-5.jpg" alt="">
                    </div>
                    <span class="name">Shahedk</span>
                    <i class="fa fa-circle away"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-6.jpg" alt="">
                    </div>
                    <span class="name">Adhamdannaway</span>
                    <i class="fa fa-circle away"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-7.jpg" alt="">
                    </div>
                    <span class="name">Ok</span>
                    <i class="fa fa-circle away"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-8.jpg" alt="">
                    </div>
                    <span class="name">Arashasghari</span>
                    <i class="fa fa-circle offline"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-9.jpg" alt="">
                    </div>
                    <span class="name">Joshaustin</span>
                    <i class="fa fa-circle offline"></i>
                </a>
                <span class="clearfix"></span>
            </li>
            <li class="list-group-item">
                <a href="#">
                    <div class="avatar">
                        <img src="~/theme2-assets/images/users/avatar-10.jpg" alt="">
                    </div>
                    <span class="name">Sortino</span>
                    <i class="fa fa-circle offline"></i>
                </a>
                <span class="clearfix"></span>
            </li>
        </ul>
    </div>
</div>

src/Pos.WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>
    @(await Component.InvokeAsync("Header"))
    @RenderSection("Styles", required: false)
</head>

<body class="fixed-left">
    <!-- Loader -->
    <div id="preloader">
        <div id="status">
            <div class="spinner">
                <div class="spinner-wrapper">
                    <div class="rotator">
                        <div class="inner-spin"></div>
                        <div class="inner-spin"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Begin page -->
    <div id="wrapper">
        <!-- Top Bar Start -->
        @(await Component.InvokeAsync("TopBar"))
        <!-- Top Bar End -->
        <!-- ========== Left Sidebar Start ========== -->
        @(await Component.InvokeAsync("Menu"))
        <!-- Left Sidebar End -->
        <!-- ============================================================== -->
        <!-- Start right Content here -->
        <!-- ============================================================== -->
        <div class="content-page">
            <!-- Start content -->
            <div class="content">
                <div class="container">
                    @RenderBody()
                </div> <!-- container -->
            </div> <!-- content -->
        </div>
        <!-- end right Content here -->

        @(await Component.InvokeAsync("Footer"))
        @(await Component.InvokeAsync("RightSidebar"))
    </div>
    <!-- END wrapper -->
    @(await Component.InvokeAsync("ThemeScripts"))
    @RenderSection("Scripts", required: false)
</body>
</html>

src/Pos.WebApplication/Views/Shared/_LayoutAuth.cshtml
<!DOCTYPE html>
<html>
@(await Component.InvokeAsync("Header"))
<body>

    <div class="account-pages"></div>
    <div class="clearfix"></div>

    <div class="wrapper-page">
        @RenderBody()
    </div>
    @(await Component.InvokeAsync("ThemeScripts"))
    @RenderSection("Scripts", required: false)
</body>
</html>